[cd]
title = "김밥레코드 ─ CD"
url = "http://gimbabrecords.com/product/list.html?cate_no=24"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[vinyl]
title = "김밥레코드 ─ Vinyl"
url = "http://gimbabrecords.com/product/list.html?cate_no=25"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cassette]
title = "김밥레코드 ─ Cassette"
url = "http://gimbabrecords.com/product/list.html?cate_no=26"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[merch]
title = "김밥레코드 ─ Movies/Merch"
url = "http://gimbabrecords.com/product/list.html?cate_no=27"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[preorder]
title = "김밥레코드 ─ Pre-Order"
url = "http://gimbabrecords.com/product/list.html?cate_no=42"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[bargainbin]
title = "김밥레코드 ─ Bargain Bin"
url = "http://gimbabrecords.com/product/list.html?cate_no=43"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_korean]
title = "김밥레코드 ─ CD ─ Korean"
url = "http://gimbabrecords.com/product/list.html?cate_no=29"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_pop-rock]
title = "김밥레코드 ─ CD ─ Pop/Rock"
url = "http://gimbabrecords.com/product/list.html?cate_no=30"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_electronic-dance]
title = "김밥레코드 ─ CD ─ Electronic/Dance"
url = "http://gimbabrecords.com/product/list.html?cate_no=31"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_soul-funk]
title = "김밥레코드 ─ CD ─ R&B/Soul/Funk"
url = "http://gimbabrecords.com/product/list.html?cate_no=44"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_hiphop]
title = "김밥레코드 ─ CD ─ Hip Hop"
url = "http://gimbabrecords.com/product/list.html?cate_no=45"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_jazz]
title = "김밥레코드 ─ CD ─ Jazz"
url = "http://gimbabrecords.com/product/list.html?cate_no=46"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_reggae]
title = "김밥레코드 ─ CD ─ Reggae"
url = "http://gimbabrecords.com/product/list.html?cate_no=47"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_soundtracks]
title = "김밥레코드 ─ CD ─ Soundtracks"
url = "http://gimbabrecords.com/product/list.html?cate_no=48"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_world]
title = "김밥레코드 ─ CD ─ World"
url = "http://gimbabrecords.com/product/list.html?cate_no=79"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_classical-crossover]
title = "김밥레코드 ─ CD ─ Classical/Crossover"
url = "http://gimbabrecords.com/product/list.html?cate_no=50"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_holiday]
title = "김밥레코드 ─ CD ─ Holiday"
url = "http://gimbabrecords.com/product/list.html?cate_no=51"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[cd_japanese]
title = "김밥레코드 ─ CD ─ Japanese"
url = "http://gimbabrecords.com/product/list.html?cate_no=90"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[vinyl_korean]
title = "김밥레코드 ─ Vinyl ─ Korean"
url = "http://gimbabrecords.com/product/list.html?cate_no=52"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"

[merch_dvd]
title = "김밥레코드 ─ Movies/Merch ─ DVD/Blu-Ray"
url = "http://gimbabrecords.com/product/list.html?cate_no=64"
entrySelector = "ul.prdList.column3 li.item.xans-record-"
titleSelector = "p.name a span"
linkSelector = "a.inner_L"
contentSelector = "span.inner_R.price"
imageSelector = "img.thumb"
waitUntil = "networkidle"
